const A={token:localStorage.jmeToken||'',user:JSON.parse(localStorage.jmeUser||'null'),view:'dashboard',data:{}};
const $=s=>document.querySelector(s);
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(m){const e=$('#toast');e.textContent=m;e.style.display='block';setTimeout(()=>e.style.display='none',3200)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...(A.token?{Authorization:'Bearer '+A.token}:{})};if(opt.body&&!(opt.body instanceof FormData)&&!opt.headers['Content-Type'])opt.headers['Content-Type']='application/json';const r=await fetch(url,opt);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
function logout(){localStorage.clear();location.reload()}
async function login(register=false){const n=register?$('#name').value.trim():'';const email=$('#email').value.trim(),password=$('#password').value;if(register&&!n)return toast('Enter your name');try{const j=await api('/api/'+(register?'register':'login'),{method:'POST',body:JSON.stringify(register?{name:n,email,password}:{email,password})});A.token=j.token;A.user=j.user;localStorage.jmeToken=j.token;localStorage.jmeUser=JSON.stringify(j.user);render()}catch(e){toast(e.message)}}
function authScreen(){$('#app').innerHTML=`<div class="auth"><div class="auth-card"><div class="brand">Judiciary <span>Made Easy</span></div><p class="muted">Your complete judiciary preparation platform</p><div id="nameWrap"><input id="name" placeholder="Full name"></div><input id="email" placeholder="Email" type="email"><input id="password" placeholder="Password" type="password"><div class="row"><button onclick="login(false)">Login</button><button class="secondary" onclick="login(true)">Create account</button></div><p class="muted">Admin demo: admin@judiciarymadeeasy.in / admin123</p></div></div>`}
function shell(){const admin=A.user.role==='admin';const items=[['dashboard','Dashboard'],['courses','Courses'],['mycourses','My Learning'],['tests','Tests'],['live','Live Classes'],['materials','Materials'],['results','Results'],['answer','Ask for Evaluation'],...(admin?[['admin','Admin Panel']]:[])];const pk=`<img src="./IMG-20260911-WA0077.jpg" style="height:32px;width:32px;border-radius:50%;border:2px solid gold">`;const jm=`<img src="./icon-192.png" style="height:30px;width:30px;border-radius:6px;background:#fff;padding:2px">`;$('#app').innerHTML=`<div class="app"><aside class="side" style="background:linear-gradient(180deg,#0f172a,#1e293b);border-right:2px solid gold"><div class="brand" style="display:flex;gap:8px;align-items:center;padding:10px;border-bottom:1px solid #334155">${pk}<div><div style="font-size:9px;color:gold;font-weight:800">PRABH KIRPA</div><div style="font-size:8px;color:#94a3b8">INSTITUTE</div><div style="display:flex;gap:5px;align-items:center;font-weight:900;color:#fff;margin-top:2px">${jm}<span style="color:gold">JME</span></div></div></div><div class="nav">${items.map(x=>`<button class="${A.view===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}</div></aside><main class="main"><div class="top"><div class="user">${esc(A.user.name)} · ${esc(A.user.role)}</div><button class="secondary" onclick="logout()">Logout</button></div><div id="page">Loading...</div></main></div>`}
async function render(){if(!A.user)return authScreen();shell();return go(A.view)}
async function go(v){A.view=v;shell();const p=$('#page');try{if(v==='dashboard')return dashboard(p);if(v==='courses')return courses(p);if(v==='mycourses')return mycourses(p);if(v==='tests')return tests(p);if(v==='live')return live(p);if(v==='materials')return materials(p);if(v==='results')return results(p);if(v==='answer')return answerPage(p);if(v==='admin')return adminPage(p)}catch(e){p.innerHTML=`<div class="card"><h2>Something went wrong</h2><p>${esc(e.message)}</p></div>`}}
async function dashboard(p){const d=await api('/api/dashboard');const mine=d.courses.filter(c=>c.enrolled);p.innerHTML=`<h1>Welcome, ${esc(d.user.name)}</h1><div class="grid"><div class="card"><div class="muted">My Courses</div><div class="stat">${mine.length}</div></div><div class="card"><div class="muted">Available Tests</div><div class="stat">${d.tests.length}</div></div><div class="card"><div class="muted">Results</div><div class="stat">${d.results.length}</div></div><div class="card"><div class="muted">Announcements</div><div class="stat">${d.announcements.length}</div></div></div><h2 style="margin-top:24px">Continue Learning</h2><div class="grid">${mine.length?mine.map(c=>courseCard(c,true)).join(''):'<div class="empty card">Purchase or enrol in a course to begin.</div>'}</div><h2 style="margin-top:24px">Announcements</h2>${d.announcements.map(a=>`<div class="card"><b>${esc(a.title)}</b><p>${esc(a.body)}</p></div>`).join('')||'<div class="empty card">No announcements yet.</div>'}`}
function courseCard(c,mine=false){return `<div class="card course"><span class="badge">${esc(c.category)}</span><h3>${esc(c.title)}</h3><p class="muted">${esc(c.description)}</p><div class="between"><span>${c.lessons||0} lessons · ${c.tests||0} tests</span><span class="price">${c.price?'₹'+Number(c.price).toLocaleString():'Free'}</span></div><div class="row" style="margin-top:12px"><button onclick="${c.enrolled?'openCourse('+c.id+')':'buyCourse('+c.id+')'}">${c.enrolled?'Open course':'Get access'}</button>${!c.enrolled&&c.price?'<button class="secondary" onclick="upiPayment('+c.id+',\''+esc(c.title).replace(/'/g,'&#39;')+'\','+c.price+')">Pay by UPI</button>':''}</div></div>`}
async function courses(p){const cs=await api('/api/courses');p.innerHTML=`<h1>Courses</h1><div class="grid">${cs.map(c=>courseCard(c)).join('')}</div>`}
async function mycourses(p){const cs=await api('/api/me/courses');p.innerHTML=`<h1>My Learning</h1><div class="grid">${cs.length?cs.map(c=>courseCard(c,true)).join(''):'<div class="empty card">No active courses.</div>'}</div>`}
async function buyCourse(id){const cs=await api('/api/courses/'+id);if(!cs.price){await api('/api/courses/'+id+'/enroll',{method:'POST'});toast('Enrolled successfully');return go('courses')}try{const o=await api('/api/payment/order',{method:'POST',body:JSON.stringify({courseId:id})});if(!o.keyId)return upiPayment(cs.id,cs.title,cs.price);new Razorpay({key:o.keyId,amount:o.amount,currency:o.currency,name:'Judiciary Made Easy',description:o.course.title,order_id:o.orderId,handler:async r=>{try{await api('/api/payment/verify',{method:'POST',body:JSON.stringify({...r,courseId:id})});toast('Payment successful. Course unlocked.');go('mycourses')}catch(e){toast(e.message)}}}).open()}catch(e){toast(e.message)}}
async function upiPayment(id,title,amount){const upi='8168667655@ptyes';const name='Judiciary Made Easy';const note=`JME Course ${id}`;const link=`upi://pay?pa=${encodeURIComponent(upi)}&pn=${encodeURIComponent(name)}&am=${encodeURIComponent(amount)}&cu=INR&tn=${encodeURIComponent(note)}`;const ok=confirm(`Pay ₹${Number(amount).toLocaleString()} via UPI to ${upi}?\n\nAfter payment, please send the payment screenshot/reference to JME for manual verification.`);if(!ok)return;location.href=link;}
async function openCourse(id){const c=await api('/api/courses/'+id),prog=await api('/api/courses/'+id+'/progress');$('#page').innerHTML=`<button class="secondary" onclick="go('mycourses')">← Back</button><h1>${esc(c.title)}</h1><div class="card"><div class="between"><b>Progress</b><span>${prog.percentage}%</span></div><div class="progress"><i style="width:${prog.percentage}%"></i></div></div><h2 style="margin-top:22px">Lessons</h2>${c.lessons.map(l=>`<div class="card between"><div><b>${esc(l.title)}</b><div class="muted">${esc(l.chapter)} · ${esc(l.duration||'')}</div></div><button onclick="watchLesson(${l.id},${id})">Watch</button></div>`).join('')||'<div class="empty card">Lessons will appear here when added by the administrator.</div>'}`}
function watchLesson(id,courseId){$('#page').innerHTML=`<button class="secondary" onclick="openCourse(${courseId})">← Course</button><h2>Lesson</h2><video controls controlsList="nodownload" src="/api/lesson/${id}/stream" onended="completeLesson(${id},${courseId})"></video><p class="muted">Lesson is marked complete when the video ends.</p>`}
async function completeLesson(id,courseId){try{await api('/api/lesson/'+id+'/progress',{method:'POST',body:JSON.stringify({completed:true})});toast('Lesson completed')}catch(e){toast(e.message)}}
async function tests(p){const ts=await api('/api/tests');p.innerHTML=`<h1>Tests & Mock Exams</h1><div class="grid">${ts.map(t=>`<div class="card"><span class="badge">${esc(t.type)}</span><h3>${esc(t.title)}</h3><p>${t.questionCount} questions · ${t.duration} minutes · ${t.marks} marks</p><button onclick="startTest(${t.id})">Start test</button></div>`).join('')}</div>`}
async function startTest(id){try{const a=await api('/api/test/'+id+'/start',{method:'POST'});showAttempt(a)}catch(e){toast(e.message)}}
function showAttempt(a){let answers=a.answers||{};const expires=new Date(a.expiresAt).getTime();const draw=()=>{$('#page').innerHTML=`<div class="between"><div><h1>${esc(a.test.title)}</h1><div class="muted">${a.questions.length} questions</div></div><div class="timer" id="timer"></div></div>${a.questions.map((q,i)=>`<div class="question"><b>${i+1}. ${esc(q.text)}</b>${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${q.id}" value="${j}" ${Number(answers[q.id])===j?'checked':''} onchange="saveAnswer('${a.attemptId}',${q.id},${j})"> ${esc(o)}</label>`).join('')}</div>`).join('')}<button onclick="submitAttempt('${a.attemptId}')">Submit test</button>`;};window.saveAnswer=(aid,q,v)=>{answers[q]=v;api('/api/test/attempt/'+aid+'/save',{method:'POST',body:JSON.stringify({answers})}).catch(()=>{})};window.submitAttempt=async aid=>{try{const r=await api('/api/test/attempt/'+aid+'/submit',{method:'POST',body:JSON.stringify({answers})});showResult(r)}catch(e){toast(e.message)}};draw();const tick=()=>{const s=Math.max(0,Math.ceil((expires-Date.now())/1000));const e=$('#timer');if(e)e.textContent=Math.floor(s/60)+':'+String(s%60).padStart(2,'0');if(s<=0){clearInterval(x);window.submitAttempt(a.attemptId)}};tick();const x=setInterval(tick,1000)}
function showResult(r){$('#page').innerHTML=`<h1>Test Result</h1><div class="grid"><div class="card"><div class="muted">Score</div><div class="stat">${r.score}/${r.total}</div></div><div class="card"><div class="muted">Percentage</div><div class="stat">${r.percentage}%</div></div><div class="card"><div class="muted">Rank</div><div class="stat">${r.rank}/${r.totalParticipants}</div></div></div><h2 style="margin-top:22px">Answer Analysis</h2>${r.analysis.map((x,i)=>`<div class="card"><b>Question ${i+1}</b><p>${x.isCorrect?'✅ Correct':'❌ Incorrect'}${x.explanation?' — '+esc(x.explanation):''}</p></div>`).join('')}`}
async function results(p){const d=await api('/api/dashboard');p.innerHTML=`<h1>My Results</h1>${d.results.slice().reverse().map(r=>`<div class="card between"><div><b>${esc(r.testTitle)}</b><div class="muted">${new Date(r.createdAt).toLocaleString()}</div></div><div><b>${r.percentage}%</b><button class="secondary" onclick="loadResult(${r.id})">View</button></div></div>`).join('')||'<div class="empty card">No submitted tests yet.</div>'}`}
async function loadResult(id){showResult(await api('/api/results/'+id))}
async function materials(p){const m=await api('/api/materials');p.innerHTML=`<h1>Study Materials</h1>${m.map(x=>`<div class="card between"><div><b>${esc(x.title)}</b><div class="muted">${esc(x.course||'General')}</div></div>${x.accessible?`<button onclick="downloadMaterial(${x.id})">Download</button>`:'<span class="badge">Locked</span>'}</div>`).join('')||'<div class="empty card">No materials yet.</div>'}`}
function downloadMaterial(id){window.open('/api/material/'+id,'_blank')}
async function live(p){const xs=await api('/api/live');p.innerHTML=`<h1>Live Classes</h1>${xs.map(x=>`<div class="card between"><div><b>${esc(x.title)}</b><div class="muted">${new Date(x.scheduledAt).toLocaleString()} · ${esc(x.courseTitle)}</div><div>${esc(x.description||'')}</div></div><div class="row"><button onclick="joinLive(${x.id})">Join</button>${x.recordingStatus==='ready'?`<button class="secondary" onclick="watchRecording(${x.id})">Recording</button>`:''}</div></div>`).join('')||'<div class="empty card">No live classes scheduled.</div>'}`}
async function joinLive(id){const x=await api('/api/live/'+id);await api('/api/live/'+id+'/attendance',{method:'POST'});window.open(x.joinUrl,'_blank')}
function watchRecording(id){$('#page').innerHTML=`<button class="secondary" onclick="go('live')">← Back</button><h2>Class Recording</h2><video controls src="/api/live/${id}/recording"></video>`}
function answerPage(p){p.innerHTML=`<h1>Ask for Evaluation</h1><div class="card"><textarea id="ansQ" rows="8" placeholder="Paste your mains answer or question here"></textarea><button onclick="sendAnswer()">Submit for evaluation</button></div>`}
async function sendAnswer(){try{await api('/api/answer',{method:'POST',body:JSON.stringify({question:$('#ansQ').value,answer:$('#ansQ').value})});toast('Submitted for evaluation');$('#ansQ').value=''}catch(e){toast(e.message)}}
async function adminPage(p){const s=await api('/api/admin/stats');p.innerHTML=`<h1>Admin Panel</h1><div class="grid">${[['Students',s.students],['Courses',s.courses],['Tests',s.tests],['Questions',s.questions],['Lessons',s.lessons],['Revenue','₹'+Number(s.revenue).toLocaleString()]].map(x=>`<div class="card"><div class="muted">${x[0]}</div><div class="stat">${x[1]}</div></div>`).join('')}</div><div class="tabs"><button onclick="adminTab('courses')">Courses</button><button onclick="adminTab('tests')">Tests</button><button onclick="adminTab('questions')">Questions</button><button onclick="adminTab('content')">Content</button><button onclick="adminTab('live')">Live</button><button onclick="adminTab('students')">Students</button><button onclick="adminTab('google')">Google</button></div><div id="adminContent"></div>`;adminTab('courses')}
window.adminTab=async t=>{const q=$('#adminContent');if(t==='courses'){const cs=await api('/api/courses');q.innerHTML=`<div class="split"><div class="card"><h3>Add course</h3><input id="ct" placeholder="Title"><input id="cc" placeholder="Category"><input id="cp" type="number" placeholder="Price"><textarea id="cd" placeholder="Description"></textarea><button onclick="addCourse()">Create</button></div><div>${cs.map(c=>`<div class="card"><b>${esc(c.title)}</b><p>₹${c.price}</p><button class="danger" onclick="delCourse(${c.id})">Delete</button></div>`).join('')}</div></div>`}
if(t==='tests'){const ts=await api('/api/tests'),cs=await api('/api/courses');q.innerHTML=`<div class="card"><h3>Create test</h3><input id="tt" placeholder="Title"><select id="tc">${cs.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}</select><input id="td" type="number" placeholder="Duration minutes" value="30"><button onclick="addTest()">Create test</button></div>${ts.map(x=>`<div class="card between"><b>${esc(x.title)}</b><button class="danger" onclick="delTest(${x.id})">Delete</button></div>`).join('')}`}
if(t==='questions'){const qs=await api('/api/admin/questions'),ts=await api('/api/tests');q.innerHTML=`<div class="card"><h3>Add MCQ</h3><select id="qt">${ts.map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('')}</select><textarea id="qq" placeholder="Question"></textarea><input id="qo" placeholder="Options separated by |"><input id="qa" type="number" placeholder="Correct option index (0,1,2...)"><textarea id="qe" placeholder="Explanation"></textarea><button onclick="addQuestion()">Add question</button></div>${qs.map(x=>`<div class="card between"><div>${esc(x.text)}</div><button class="danger" onclick="delQuestion(${x.id})">Delete</button></div>`).join('')}`}
if(t==='content'){const cs=await api('/api/courses');q.innerHTML=`<div class="split"><div class="card"><h3>Upload material</h3><form id="matForm"><input name="title" placeholder="Title"><select name="courseId"><option value="">General</option>${cs.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}</select><input type="file" name="file" required><button>Upload</button></form></div><div class="card"><h3>Upload lesson</h3><form id="lessonForm"><select name="courseId">${cs.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}</select><input name="title" placeholder="Lesson title"><input name="chapter" placeholder="Chapter"><input name="duration" placeholder="Duration"><input name="order" type="number" value="1"><input type="file" name="video" accept="video/*" required><button>Upload video</button></form></div></div>`;$('#matForm').onsubmit=async e=>{e.preventDefault();await api('/api/admin/material',{method:'POST',body:new FormData(e.target)});toast('Material uploaded')};$('#lessonForm').onsubmit=async e=>{e.preventDefault();await api('/api/admin/lesson',{method:'POST',body:new FormData(e.target)});toast('Lesson uploaded')}}
if(t==='live'){const cs=await api('/api/courses');const xs=await api('/api/admin/live');q.innerHTML=`<div class="card"><h3>Schedule live class</h3><input id="lt" placeholder="Title"><select id="lc"><option value="">All students</option>${cs.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}</select><input id="ls" type="datetime-local"><button onclick="addLive()">Schedule</button></div>${xs.map(x=>`<div class="card between"><div><b>${esc(x.title)}</b><div>${new Date(x.scheduledAt).toLocaleString()} · ${esc(x.recordingStatus)}</div></div><div class="row"><button onclick="liveStart(${x.id})">Start</button><button class="secondary" onclick="liveEnd(${x.id})">End</button><button class="danger" onclick="liveDelete(${x.id})">Delete</button></div></div>`).join('')}`}
if(t==='students'){const xs=await api('/api/admin/students');q.innerHTML=`<table class="table"><tr><th>Name</th><th>Email</th><th>Courses</th></tr>${xs.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${x.courses.length}</td></tr>`).join('')}</table>`}
if(t==='google'){const x=await api('/api/admin/google/status');q.innerHTML=`<div class="card"><h3>Google Workspace</h3><p>Configured: ${x.configured?'Yes':'No'}<br>Connected: ${x.connected?'Yes':'No'}<br>${esc(x.email)}</p><button onclick="connectGoogle()">Connect official JME account</button> <button class="secondary" onclick="testGoogle()">Test connection</button> <button class="danger" onclick="disconnectGoogle()">Disconnect</button></div>`}}
window.addCourse=async()=>{await api('/api/admin/course',{method:'POST',body:JSON.stringify({title:$('#ct').value,category:$('#cc').value,price:Number($('#cp').value||0),description:$('#cd').value})});toast('Course created');adminTab('courses')}
window.delCourse=async id=>{if(confirm('Delete course?')){await api('/api/admin/course/'+id,{method:'DELETE'});adminTab('courses')}}
window.addTest=async()=>{await api('/api/admin/test',{method:'POST',body:JSON.stringify({title:$('#tt').value,courseId:Number($('#tc').value),duration:Number($('#td').value||30)})});toast('Test created');adminTab('tests')}
window.delTest=async id=>{await api('/api/admin/test/'+id,{method:'DELETE'});adminTab('tests')}
window.addQuestion=async()=>{await api('/api/admin/question',{method:'POST',body:JSON.stringify({testId:Number($('#qt').value),text:$('#qq').value,options:$('#qo').value.split('|').map(x=>x.trim()).filter(Boolean),answer:Number($('#qa').value),explanation:$('#qe').value})});toast('Question added');adminTab('questions')}
window.delQuestion=async id=>{await api('/api/admin/question/'+id,{method:'DELETE'});adminTab('questions')}
window.addLive=async()=>{await api('/api/admin/live',{method:'POST',body:JSON.stringify({title:$('#lt').value,courseId:$('#lc').value||null,scheduledAt:$('#ls').value})});toast('Class scheduled');adminTab('live')}
window.liveStart=async id=>{await api('/api/admin/live/'+id+'/start',{method:'POST'});adminTab('live')}
window.liveEnd=async id=>{await api('/api/admin/live/'+id+'/end',{method:'POST',body:'{}'});adminTab('live')}
window.liveDelete=async id=>{await api('/api/admin/live/'+id,{method:'DELETE'});adminTab('live')}
window.connectGoogle=async()=>{const x=await api('/api/admin/google/connect',{method:'POST'});location.href=x.url}
window.testGoogle=async()=>{const x=await api('/api/admin/google/test',{method:'POST'});toast('Connected as '+x.email)}
window.disconnectGoogle=async()=>{await api('/api/admin/google/disconnect',{method:'POST'});toast('Disconnected');adminTab('google')}
render();
